<?php $active=$_GET['route']??'dashboard';$logged=isset($_SESSION['user']); ?>
<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#773357"><title><?= e($title??'Padrón') ?> · PIPAS Tlalpan</title><link rel="icon" href="<?= e(asset('logos/alcaldia-tlalpan-guinda.png')) ?>"><link rel="stylesheet" href="<?= e(asset('css/app.css').'?v='.filemtime(__DIR__.'/../../public/css/app.css')) ?>"><script src="<?= e(asset('js/app.js').'?v='.filemtime(__DIR__.'/../../public/js/app.js')) ?>" defer></script></head>
<body class="<?= $logged?'app-body':'auth-body' ?>">
<?php if($logged): ?>
<a class="skip" href="#main">Ir al contenido</a><div class="mobile-bar"><strong><?= icon('drop') ?> PIPAS <span>Tlalpan</span></strong><button class="icon-button" id="menu-toggle" aria-label="Abrir menú" aria-expanded="false" aria-controls="sidebar"><?= icon('menu') ?></button></div><button id="backdrop" class="backdrop" aria-label="Cerrar menú" hidden></button>
<aside class="sidebar" id="sidebar"><div class="sidebar-government"><img src="<?= e(asset('logos/alcaldia-tlalpan-guinda.png')) ?>" alt="Alcaldía Tlalpan"><span>PLATAFORMA INSTITUCIONAL</span></div><a href="<?= e(url()) ?>" class="brand"><span class="brand-mark"><?= icon('drop') ?></span><span><strong>PIPAS<span class="brand-dot">.</span></strong><small>ALCALDÍA TLALPAN</small></span></a>
<div class="nav-caption">GESTIÓN DEL AGUA</div><nav aria-label="Menú principal">
<?php foreach([['dashboard','grid','Resumen'],['padron','users','Padrón de beneficiarios'],['nuevo','plus','Alta de beneficiario'],['bloqueos','lock','Bloqueo y reactivación'],['dotaciones','drop','Dotación y viajes']] as [$r,$i,$label]): if(!can('manage') && in_array($r,['nuevo','bloqueos','dotaciones']))continue;$selected=$active===$r || ($r==='padron' && in_array($active,['detalle','editar'])); ?>
<a class="nav-link <?= $selected?'active':'' ?>" <?= $selected?'aria-current="page"':'' ?> href="<?= e(url($r)) ?>"><?= icon($i) ?><span><?= $label ?></span><?php if($selected):?><span class="nav-dot"></span><?php endif;?></a><?php endforeach;?></nav>
<?php if(can('manage')):?><div class="nav-caption">ADMINISTRACIÓN</div><nav aria-label="Administración"><a class="nav-link <?= $active==='catalogos'?'active':'' ?>" href="<?= e(url('catalogos')) ?>"><?= icon('settings') ?>Catálogos</a><a class="nav-link <?= $active==='usuarios'?'active':'' ?>" href="<?= e(url('usuarios')) ?>"><?= icon('users') ?>Usuarios del sistema</a></nav><?php endif;?>
<div class="sidebar-bottom"><div class="institution"><img src="<?= e(asset('logos/alcaldia-tlalpan-guinda.png')) ?>" alt="Alcaldía Tlalpan"><span>JUD de Pipas<br>Gestión de padrón de beneficiarios</span></div><div class="profile"><a href="<?= e(url('cuenta')) ?>" class="avatar"><?= e(mb_substr($_SESSION['user']['nombre'],0,1)) ?></a><a class="profile-name" href="<?= e(url('cuenta')) ?>"><strong><?= e($_SESSION['user']['nombre']) ?></strong><small><?= can('manage')?'Administración · ROOT':'Captura · ALTAS' ?></small></a><form action="<?= e(url('logout')) ?>" method="post"><?= csrf() ?><button class="icon-button" title="Cerrar sesión" aria-label="Cerrar sesión"><?= icon('logout') ?></button></form></div></div></aside>
<div class="workspace"><header class="topbar"><div><span class="breadcrumb">Sistema de distribución de agua</span><span class="crumb-sep">/</span><strong><?= e($title??'Padrón') ?></strong></div><div class="topbar-right"><span class="live-dot"></span> Módulo Padrón <span class="date"><?= date('d / m / Y') ?></span></div></header><main id="main" class="main">
<?php if(isset($_SESSION['flash'])):$notice=$_SESSION['flash'];unset($_SESSION['flash']);?><div class="alert <?= e($notice['type']) ?>" role="status"><?= icon('check') ?><span><?= e($notice['message']) ?></span></div><?php endif; ?>
<?php if($config['environment']==='testing'):?><div class="alert info">ENTORNO DE PRUEBAS · Datos ficticios. Separado del padrón operativo.</div><?php endif;?>
<?= $content ?></main><footer class="app-footer"><span>Alcaldía Tlalpan · Sistema de Pipas</span><span>Servicio público, cerca de ti.</span></footer></div>
<?php else: ?><?= $content ?><?php endif; ?></body></html>
