<a class="back-link" href="<?= e(url('detalle',['id'=>$record['id_padron']])) ?>">← Volver a la ficha</a><section class="page-heading"><div><span class="eyebrow">PIPAS / CONTROL DEL SERVICIO</span><h1><?= e($title) ?></h1><p>Revisa los datos y registra el motivo de la operación.</p></div></section>
<?php if($error):?><div class="alert danger" role="alert"><?= e($error) ?></div><?php endif;?>
<div class="operation-layout"><section class="card form-section"><div class="operation-person"><span class="avatar"><?= e(mb_substr($record['nombre'],0,1)) ?></span><div><strong><?= e($record['nombre_completo']) ?></strong><p>Folio <?= e($record['folio']) ?> · <?= e($record['colonia_nombre']) ?></p></div><?= badge($record['status_padron']) ?></div>
<?php if($action==='reactivar'):foreach($history['bloqueos'] as $b):if($b['status_padron_bloqueo']!=='1')continue;?><div class="alert warning"><div><strong>Antecedente: <?= e($b['motivo']) ?></strong><p><?= e($b['desc_padron_bloqueado']) ?></p><small><?= e($b['fecha_padron_bloqueado']) ?></small></div></div><?php endforeach;endif;?>
<form method="post" class="operation-form"><?= csrf() ?><input type="hidden" name="version" value="<?= e($_POST['version']??$record['version']) ?>">
<?php if($action==='bloquear'):?><label>Motivo del bloqueo *<select name="motivo" required><option value="">Selecciona un motivo</option><option value="1" <?= ($_POST['motivo']??'')==='1'?'selected':'' ?>>No entregó hoja rosa</option><option value="2" <?= ($_POST['motivo']??'')==='2'?'selected':'' ?>>Compra con acta</option></select></label><?php endif;?>
<?php if($action==='dotacion'):?><div class="readonly-field"><span>Dotación actual</span><strong><?= e($record['dotacion']) ?> viajes por mes</strong></div><label>Nueva dotación mensual *<select name="dotacion" required><option value="">Selecciona la nueva cuota</option><?php for($i=1;$i<=10;$i++):if($i===(int)$record['dotacion'])continue;?><option value="<?= $i ?>" <?= (int)($_POST['dotacion']??0)===$i?'selected':'' ?>><?= $i ?> <?= $i===1?'viaje':'viajes' ?> por mes</option><?php endfor;?></select></label><?php endif;?>
<?php if($action==='extraordinaria'):?><label>Viajes adicionales autorizados *<select name="num_dotacion" required><?php for($i=1;$i<=10;$i++):?><option value="<?= $i ?>" <?= (int)($_POST['num_dotacion']??1)===$i?'selected':'' ?>><?= $i ?> <?= $i===1?'viaje':'viajes' ?></option><?php endfor;?></select></label><label>Autoridad que autoriza *<select name="autorizo_id_autorizo" required><option value="">Selecciona la autoridad</option><?php foreach($catalogs['autorizo'] as $a):?><option value="<?= $a['id'] ?>" <?= (string)($_POST['autorizo_id_autorizo']??'')===(string)$a['id']?'selected':'' ?>><?= e($a['nombre']) ?></option><?php endforeach;?></select></label><?php if(!$catalogs['autorizo']):?><div class="alert info">Agrega una autoridad en <a href="<?= e(url('catalogos')) ?>">Catálogos</a> para autorizar viajes.</div><?php endif;?><?php endif;?>
<label><?= $action==='reactivar'?'Justificación de la reactivación':'Justificación' ?> *<textarea name="justificacion" required maxlength="500" rows="5" placeholder="Describe el motivo y los antecedentes de la operación…"><?= e($_POST['justificacion']??'') ?></textarea><small>Máximo 500 caracteres. Quedará registrada en la bitácora.</small></label><div class="form-footer"><a class="button secondary" href="<?= e(url('detalle',['id'=>$record['id_padron']])) ?>">Cancelar</a><button type="submit" class="button <?= $action==='bloquear'?'danger':'primary' ?>" <?= $action==='extraordinaria'&&!$catalogs['autorizo']?'disabled':'' ?>><?= icon('check') ?> Confirmar operación</button></div></form></section><aside class="guide-note"><span class="stat-icon"><?= icon($action==='dotacion'||$action==='extraordinaria'?'drop':'lock') ?></span><h3>Antes de confirmar</h3><p><?= ['bloquear'=>'El beneficiario quedará suspendido para nuevas autorizaciones. El motivo se conservará en su expediente.','reactivar'=>'Se concluirá el bloqueo vigente y el beneficiario volverá a estar activo.','dotacion'=>'La cuota anterior quedará en el historial. Solo habrá una dotación vigente por domicilio.','extraordinaria'=>'La autorización adicional no modifica la cuota regular. Este permiso no registra un cobro ni una entrega.'][$action] ?></p><p class="small">Operador: <?= e($_SESSION['user']['nombre']) ?></p></aside></div>
